name: kanvsdarts
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.8
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - alembic
      - annotated-types
      - anyio
      - argon2-cffi
      - argon2-cffi-bindings
      - arviz
      - asttokens
      - attrs
      - autora[theorist-darts]
      - babel
      - bambi
      - bayesian-optimization
      - beautifulsoup4
      - bleach
      - bottle
      - cachetools
      - certifi
      - cffi
      - charset-normalizer
      - click
      - cloudpickle
      - colorama
      - colorlog
      - comm
      - cons
      - contourpy
      - cycler
      - debugpy
      - decorator
      - defusedxml
      - dill
      - docker-pycreds
      - etuples
      - executing
      - fastjsonschema
      - filelock
      - fonttools
      - formulae
      - fsspec
      - gitdb
      - gitpython
      - graphviz
      - greenlet
      - h5netcdf
      - h5py
      - hddm-wfpt
      - hssm
      - huggingface-hub
      - idna
      - ipykernel
      - ipython
      - ipython-genutils
      - ipython-pygments-lexers
      - jax
      - jaxlib
      - jedi
      - jinja2
      - joblib
      - json5
      - jsonschema
      - jsonschema-specifications
      - jupyter-client
      - jupyter-core
      - jupyter-server
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - kiwisolver
      - logical-unification
      - mako
      - markdown-it-py
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mdurl
      - minikanren
      - mistune
      - ml-dtypes
      - mpmath
      - multipledispatch
      - multiprocess
      - nbclassic
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - networkx
      - notebook-shim
      - numpy
      - numpyro
      - onnx
      - opt-einsum
      - optuna
      - optuna-dashboard
      - pykan
      - packaging
      - pandas
      - pandocfilters
      - parso
      - pathos
      - pillow
      - platformdirs
      - pox
      - ppft
      - prometheus-client
      - prompt-toolkit
      - protobuf
      - psutil
      - pure-eval
      - pycparser
      - pydantic
      - pydantic-core
      - pygments
      - pymc
      - pyparsing
      - pytensor
      - python-dateutil
      - pytz
      - referencing
      - requests
      - rich
      - rpds-py
      - scikit-learn
      - scipy
      - seaborn
      - send2trash
      - sentry-sdk
      - setproctitle
      - shellingham
      - six
      - smmap
      - sniffio
      - sortedcontainers
      - soupsieve
      - sqlalchemy
      - ssm-simulators
      - stack-data
      - sympy
      - terminado
      - threadpoolctl
      - tinycss2
      - toolz
      - torch
      - tornado
      - tqdm
      - traitlets
      - typer
      - typing-extensions
      - typing-inspection
      - tzdata
      - urllib3
      - wandb
      - wcwidth
      - webencodings
      - websocket-client
      - xarray
      - xarray-einstats
